---
title: "Homework 6"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(viridis)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 2

1. Loaded the data
2. Created the following variables:
   * city_state
   * case_solved: binary variable where 0 = case unresolved, 1 = case resolved
3. Filtered the data in the following ways:
   * For city_state, removed Dallax, TX; Phoenix, AZ; Kansas City, MO; Tulsa, AL
   * For victim_race, only included White & Black
5. Converted victim_age's data type from char to numeric

```{r}
homicide_df = read.csv('data/homicide.csv') %>% 
  mutate(city_state = str_c(city, state, sep = ", "),
         case_solved = case_when(
           disposition == "Closed without arrest" ~ "0",
           disposition == "Open/No arrest" ~ "0",
           disposition == "Closed by arrest" ~ "1")) %>% 
  filter(city_state != "Tulsa, AL", 
         city_state != "Dallas, TX", 
         city_state != "Phoenix, AZ", 
         city_state != "Kansas City, MO", 
         victim_race %in% c("White" ,"Black")) %>% 
  mutate(victim_age = as.numeric(victim_age))
```

